[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]

remappings = ['@openzeppelin=lib/openzeppelin-contracts', "forge-std=lib/forge-std/src", "murky/=lib/murky/"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
